Fix Windows CI (#533)
Previous version of install-setuptools makefile target was causing the following error in CI:

ERROR: To modify pip, please run the following command:
python.exe -m pip install --upgrade pip setuptools wheel
make: *** [Makefile:15: install-setuptools] Error 1